"""add_user_id_to_activity

Revision ID: 65d1413adc6a
Revises: 264edb7aeadc
Create Date: 2026-02-19 17:26:31.780917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d1413adc6a'
down_revision: Union[str, Sequence[str], None] = '264edb7aeadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('_user_activity_uc', ['user_id', 'name'])
        batch_op.create_index(batch_op.f('ix_activities_user_id'), ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_user_id'))
        batch_op.drop_constraint('_user_activity_uc', type_='unique')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
